@echo off
echo Starting Google Scraper UI...
echo Checking for dependencies...
python -m pip install -r requirements.txt --quiet
echo.
echo Launching the application...
python -m streamlit run app.py
pause
